# Webserver Role Tasks
---
- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Copy Nginx config
  template:
    src: "{{ nginx_config_file }}"
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy custom index.html
  copy:
    src: "{{ nginx_default_html_file }}"
    dest: /var/www/html/index.html
